using Ridge.Setup;
using Xunit.Abstractions;

namespace Ridge.Extensions.Xunit;

/// <summary>
///     Ridge logging options extensions.
/// </summary>
public static class RidgeOptionsLoggingExtensions
{
    /// <summary>
    ///     Use XUnit logger which will be used to log requests and responses generated by ridge.
    ///     To read more about <see cref="ITestOutputHelper" /> see documentation https://xunit.net/docs/capturing-output.
    /// </summary>
    /// <param name="ridgeOptions">Options to edit.</param>
    /// <param name="outputTestHelper"><see cref="ITestOutputHelper" /> used to write logs.</param>
    /// <returns></returns>
    public static RidgeOptions UseXunitLogWriter(
        this RidgeOptions ridgeOptions,
        ITestOutputHelper outputTestHelper)
    {
        ridgeOptions.LogWriter = new XunitLogWriter(outputTestHelper);
        return ridgeOptions;
    }
}
