using System.Text;

namespace RidgeSourceGenerator;

public static class GeneralMethodsGenerationHelper
{
    private const string Header = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Ridge source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

    public static string GenerateExtensionClass(
        StringBuilder sb,
        string controllerName,
        string? @namespace,
        CancellationToken cancellationToken)
    {
        var className = $"{controllerName}Caller";
        
        sb.Append(Header);
        sb.Append(@"
#nullable enable

using Ridge.Caller;
using Ridge.LogWriter;
using Ridge.Pipeline.Public;
using Ridge.Serialization;
using Ridge.Transformers;
using Ridge.Response;
using Ridge.ActionInfo;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Reflection;
using System.Threading.Tasks;
");
        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.Append(@"namespace ").AppendLine(@namespace);
            sb.AppendLine("{");
        }

        cancellationToken.ThrowIfCancellationRequested();

        sb.Append(@"
/// <summary>
/// Generated Api client for tests. Calls <see cref=""");
        sb.Append(@namespace);
        sb.Append(".");
        sb.Append(className);
        sb.AppendLine("\" />");
        sb.Append(@"/// </summary>
public partial class ");
        sb.Append(className);
        sb.Append(" : IControllerCaller");
        sb.Append(@"
{
    HttpClient IControllerCaller.HttpClient { get; set; } = null!;
    IServiceProvider IControllerCaller.ServiceProvider { get; set; } = null!;
    ILogWriter? IControllerCaller.LogWriter { get; set; } = null!;
    IRequestResponseSerializer? IControllerCaller.RidgeSerializer { get; set; } = null!;
    RequestBuilder IControllerCaller.RequestBuilder { get; set; }  = new();

    /// <summary>
    ///     Create controller factory.
    /// </summary>
    /// <param name=""httpClient"">HttpClient used to call the server.</param>
    /// <param name=""serviceProvider"">ServiceProvider used to gather information about the server.</param>
    /// <param name=""logWriter"">
    ///     Used to log requests and responses from server.
    ///     Use <see cref=""XunitLogWriter"" /> or <see cref=""NunitLogWriter"" /> or <see cref=""NunitProgressLogWriter""/> or implement custom <see cref=""ILogWriter"" />
    /// </param>
    /// <param name=""ridgeSerializer"">
    ///     Serializer used to serialize and deserialize requests.
    ///     Serializer is by default chosen based on asp.net settings. If you need custom serializer implement
    ///     <see cref=""IRequestResponseSerializer"" />.
     /// </param>
    public ");
        sb.Append(className);
        sb.AppendLine(@"(
        HttpClient httpClient,
        IServiceProvider serviceProvider,
        ILogWriter? logWriter = null,
        IRequestResponseSerializer? ridgeSerializer = null)
    {
        ((IControllerCaller)this).HttpClient = httpClient;
        ((IControllerCaller)this).ServiceProvider = serviceProvider;
        ((IControllerCaller)this).LogWriter = logWriter;
        ((IControllerCaller)this).RidgeSerializer = ridgeSerializer;
    }

    /// <summary>
    ///     Add <see cref=""IHttpRequestPipelinePart""/> which will be used to transform <see cref=""HttpRequestMessage""/>s.
    /// </summary>
    /// <param name=""httpRequestPipelineParts""><see cref=""IHttpRequestPipelinePart""/> to add.</param>
    public void AddHttpRequestPipelineParts(
        params IHttpRequestPipelinePart[] httpRequestPipelineParts)
    {
        ((IControllerCaller)this).RequestBuilder.AddHttpRequestPipelineParts(httpRequestPipelineParts);
    }

    /// <summary>
    ///     Adds <see cref=""IActionInfoTransformer""/> which will be later used to transform <see cref=""IActionInfo""/>s.
    /// </summary>
    /// <param name=""actionInfoTransformers""><see cref=""IActionInfoTransformer""/>  to add.</param>
    public void AddActionInfoTransformers(
        params IActionInfoTransformer[] actionInfoTransformers)
    {
        ((IControllerCaller)this).RequestBuilder.AddActionInfoTransformers(actionInfoTransformers);
    }

    /// <summary>
    ///     Adds headers to the requests. This method actually adds <see cref=""IActionInfoTransformer""/>
    ///     which then adds the header to requests.
    /// </summary>
    /// <param name=""headers"">Headers to add.</param>
    public void AddHeaders(params (string Key, string? Value)[] headers)
    {
        ((IControllerCaller)this).RequestBuilder.AddHeaders(headers);
    }

    /// <summary>
    ///     Adds <see cref=""AuthenticationHeaderValue""/> to the requests. This method actually adds <see cref=""IActionInfoTransformer""/>
    ///     which then adds the header to requests.
    /// </summary>
    /// <param name=""authenticationHeaderValue""><see cref=""AuthenticationHeaderValue""/> to add.</param>
    public void AddAuthenticationHeaderValue(
        AuthenticationHeaderValue authenticationHeaderValue)
    {
        ((IControllerCaller)this).RequestBuilder.AddAuthenticationHeaderValue(authenticationHeaderValue);
    }
    ");
        sb.AppendLine("}");

        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.AppendLine("}");
        }

        sb.Append("#nullable restore");

        cancellationToken.ThrowIfCancellationRequested();
        return sb.ToString();
    }
}
