using RidgeSourceGenerator.Dtos;
using System.Text;

namespace RidgeSourceGenerator.GenerationHelpers;

public static class ControllerCallerGenerationHelper
{
    private const string Header = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Ridge source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

    public static string GenerateExtensionClass(
        StringBuilder sb,
        ControllerToGenerate controllerToGenerate,
        IEnumerable<MethodToGenerate> generatedMethods,
        CancellationToken cancellationToken)
    {
        var className = $"{controllerToGenerate.Name}Caller";

        sb.Append(Header);
        sb.AppendLine(
            """
            #nullable enable
            #pragma warning disable CS0419

            using Ridge.HttpRequestFactoryMiddlewares;
            using Ridge;
            using Ridge.LogWriter;
            using Ridge.Serialization;
            using Ridge.Response;
            using System;
            using System.Collections.Generic;
            using System.Net.Http;
            using System.Net.Http.Headers;
            using System.Reflection;
            using System.Threading.Tasks;
            using Ridge.Parameters.AdditionalParams;
            """
        );
        
        if (!string.IsNullOrEmpty(controllerToGenerate.Namespace))
        {
            sb.AppendLine(
                $$"""
                namespace {{controllerToGenerate.Namespace}}
                {
                """ 
            );
        }

        cancellationToken.ThrowIfCancellationRequested();

        sb.Append(
                $$"""
                    /// <summary>
                    /// Generated Api caller. Calls <see cref="{{controllerToGenerate.Namespace}}.{{controllerToGenerate.Name}}" />
                    /// </summary>
                    public class {{className}}
                    {
                        private readonly ApplicationCaller _applicationCaller;
                        /// <summary>
                        /// Creates controller caller. 
                        /// </summary>
                        /// <param name="httpClient">
                        ///     HttpClient which will be used to call application.
                        /// </param>
                        /// <param name="serviceProvider">
                        ///     Application serviceProvider.
                        /// </param>
                        public {{className}}(HttpClient httpClient, IServiceProvider serviceProvider)
                        {
                            _applicationCaller = new ApplicationCaller(httpClient, serviceProvider);
                        }
                        
                """);

        foreach (var methodToGenerate in generatedMethods)
        {
            sb.Append(methodToGenerate.GenerateMethod(cancellationToken));
        }

        sb.AppendLine(" }");

        if (!string.IsNullOrEmpty(controllerToGenerate.Namespace))
        {
            sb.AppendLine("}");
        }

        cancellationToken.ThrowIfCancellationRequested();
        sb.AppendLine("#pragma warning restore CS0419");
        
        sb.Append("#nullable restore");
        return sb.ToString();
    }
}
