name: Test

on:
    push:
        branches:
            - '**'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup .NET Core
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 5.0.103
            -   name: Setup .NET Core
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 3.1.201
            -   name: Setup .NET Core
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 3.0.103
            -   name: Run tests general
                run: |
                    cd 'Tests/RidgeTests'
                    dotnet test
            -   name: Run tests xunit
                run: |
                    cd 'Tests/RidgeXunitTest'
                    dotnet test
