name: Test

on:
    push:
        branches:
            - '**'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup .NET Core
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: |
                        6.0
                        7.0
                        8.0
                        9.0
            -   name: Run tests general
                run: |
                    cd 'Tests/RidgeTests'
                    dotnet test
            -   name: Run tests xunit
                run: |
                    cd 'Tests/RidgeXunitTest'
                    dotnet test
